title:  Blog | Soham's Website
iconURL: assets/default-icon.png
theme: jekyll-theme-time-machine

# for a clean URL
permalink: :slug

social:

  github: sohamdd0109

plugins:
 - jekyll-feed
 - jekyll-seo-tag

### comments & analytics
hyvor_talk_website_id: 14
google_analytics: UA-NNNNNNNN-N
